import React from 'react'
import { Metadata } from 'next'

type Props = {}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const about = (props: Props) => {
  return (
    <>
      <p>About</p>
    </>
  )
}

export default about
