import Navigation from '@/components/Navigation'
import { Montserrat } from 'next/font/google'
// import Head from 'next/head'

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-mont',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      {/* <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <body
        className={`${montserrat.variable} font-mont bg-light w-full min-h-screen`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  )
}
